version: "3.7"

services:
  node:
    image: node:14.17.0
    container_name: vue
    tty: true
    ports:
      - "3000:3000"
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
